#grep()
name="Data analytics"
v=c('a','d','n')
grepl("a",v)
grep("n",v)
install.packages("stringr")
library(stringr)
#like grepl
str_detect(name,"D")
#like grep
str_which(name,"D")
#nchar()
greet="Hello Class!"
nchar(greet)
#paste()
paste("Hello ","Good morning!!!")
paste("Hello ","Good morning!!!",sep="-")
paste("BCA 5 Div",c(1:3),sep=":")
#cat()
cat("learn","DAR")
cat("Learn DAR in BCA5",file="Dar.txt")
getwd()
#sprintf()
sprintf("In sem %d , we have many Subjects to %s",5,"Study")
#substr()
substr("This is my class",12,16) 
substr("This is my class",1,4)
str <- c("program", "with", "new", "language")
substr(str, 1,3) 
toupper("this is example")
tolower("THIS IS EXAMPLE")
strsplit()